# Generated by Django 5.0.7 on 2024-07-28 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_recipe_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='rating',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
    ]
