# Generated by Django 5.0.7 on 2024-07-29 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_cauntry_image_alter_ingredient_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dessert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('image', models.ImageField(upload_to='images')),
                ('ngredients', models.ManyToManyField(blank=True, to='main.ingredient')),
            ],
        ),
    ]
