# Generated by Django 5.0.7 on 2024-07-29 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_dessert'),
    ]

    operations = [
        migrations.AddField(
            model_name='dessert',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
