# Generated by Django 5.0.7 on 2024-07-29 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_remove_about_created_at_remove_about_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='email',
            field=models.EmailField(blank=True, max_length=200, null=True),
        ),
    ]
