# Generated by Django 5.0.7 on 2024-07-29 15:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_review_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='foods',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.recipe'),
        ),
    ]
