# Generated by Django 5.0.7 on 2024-07-29 15:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_review_foods'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='foods',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='review', to='main.recipe'),
        ),
    ]
