# Generated by Django 5.0.7 on 2024-07-30 08:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_alter_review_foods'),
    ]

    operations = [
        migrations.DeleteModel(
            name='About',
        ),
    ]
